# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'APReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APReader
  pod 'MSAL', '~> 1.1.1'
  pod 'MSGraphClientSDK', ' ~> 1.0.0'
  pod 'MSGraphClientModels', '~> 1.3.0'
  
  pod 'Tiercel'
  pod 'SVProgressHUD'
  pod 'DZNEmptyDataSet'
  pod 'TouchDraw'

  pod 'AppCenter'

end
